graphe:
    resource: "@GrapheBundle/Resources/config/routing.yml"
    prefix:   /

maisonretraite_resident:
    resource: "@MaisonretraiteBundle/Controller/ResidentController.php"
    type:     annotation

maisonretraite_maison:
    resource: "@MaisonretraiteBundle/Controller/MaisonController.php"
    type:     annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

activite_activite:
    resource: "@ActiviteBundle/Controller/ActiviteController.php"
    type:     annotation

activite_animateur:
    resource: "@ActiviteBundle/Controller/AnimateurController.php"
    type:     annotation

prestationsante:
    resource: "@PrestationsanteBundle/Resources/config/routing.yml"
    prefix:   /

maisonretraite:
    resource: "@MaisonretraiteBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

dons:
    resource: "@DonsBundle/Resources/config/routing.yml"
    prefix:   /

activite:
    resource: "@ActiviteBundle/Resources/config/routing.yml"
    prefix:   /

action_benevolat:
    resource: "@ActionBenevolatBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
