<?php

namespace MaisonretraiteBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResidentRepository extends \Doctrine\ORM\EntityRepository
{
    public function CountNbPersonne($id)
    {
        $query = $this->getEntityManager()->createQuery("select count (e.idResident) as nb from MaisonretraiteBundle:Resident e WHERE  e.idMaison=:n  ")
            ->setParameter('n',$id);
        return $query->getSingleScalarResult();
    }
}
