<?php

namespace EventBundle\Repository;

/**
 * SponsorEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
