maisonretraite_homepage:
    path:     /
    defaults: { _controller: MaisonretraiteBundle:Default:index }


#MAISON
ajouter_ma:
    path:     /ajoutema
    defaults: { _controller: MaisonretraiteBundle:Maison:ajoutema }

affiche_ma:
    path:     /affichema
    defaults: { _controller: MaisonretraiteBundle:Maison:affichema }

all_M:
    path:     /allM
    defaults: { _controller: MaisonretraiteBundle:Maison:allM }

delete_ma:
        path:     /deletema/{id}
        defaults: { _controller: MaisonretraiteBundle:Maison:deletema }

edit_ma:
    path:     /editma/{id}
    defaults: { _controller: MaisonretraiteBundle:Maison:editma }

Maison_recherche:
    path:     /recherche
    defaults: { _controller: MaisonretraiteBundle:Maison::recherche }


#RESIDENT
ajout_re:
    path:     /ajoutre
    defaults: { _controller: MaisonretraiteBundle:Resident:ajoutre }

affiche_re:
    path:     /affichere
    defaults: { _controller: MaisonretraiteBundle:Resident:affichere }
all_re:
    path:     /allre
    defaults: { _controller: MaisonretraiteBundle:Resident:allre }
find_re:
    path:     /findre/{id}
    defaults: { _controller: MaisonretraiteBundle:Resident:findre }
add_re:
    path:     /addre
    defaults: { _controller: MaisonretraiteBundle:Resident:addre }

delete_re:
        path:     /deletere/{id}/{idMaison}
        defaults: { _controller: MaisonretraiteBundle:Resident:deletere }
delete_reA:
    path:     /deletere/{id}/{idMaison}
    defaults: { _controller: MaisonretraiteBundle:Resident:deletereA }
edit_re:
    path:     /editre/{id}
    defaults: { _controller: MaisonretraiteBundle:Resident:editre }
validerR:
    path:     /valider/{id}/{idMaison}
    defaults: { _controller: MaisonretraiteBundle:Resident:valider }

export:
        path:     /export
        defaults: { _controller: MaisonretraiteBundle:Resident:export }

affiche_reA:
    path:     /affichereA
    defaults: { _controller: MaisonretraiteBundle:Resident:affichereA }

delete_mobile:
    path:     /deleteMobile/{id}
    defaults: { _controller: MaisonretraiteBundle:Resident:deleteMobile }

modif_mobile:
    path:     /modifMobile/{id}/{prenom}/{nom}/{age}/{sexe}/{responsable}/{telephone}/
    defaults: { _controller: MaisonretraiteBundle:Resident:modifMobile }

ajouter_Resident_Mobile:
    path:     /ajouterResidentMobile/{idM}
    defaults: { _controller: MaisonretraiteBundle:Resident:ajouterResidentMobile }

Valider_Mobile:
    path:     /ValiderMobile/{idM}
    defaults: { _controller: MaisonretraiteBundle:Resident:ValiderMobile }